### ISSUE TITLE
Twisted NameError: name 'CertificateOptions' is not defined

### ISSUE THREAD

**Issue by baotang2118** [spotware/OpenApiPy#19]
Hello

I run the example [ConsoleSample](https://github.com/spotware/OpenApiPy/tree/main/samples/ConsoleSample) and [jupyter](https://github.com/spotware/OpenApiPy/tree/main/samples/jupyter) and found this error.

```
(.venv) baotd@baotd-ThinkPad-T14-Gen-2i:~/Documents/bot-trader/collection-engine$ python testproto.py 
Host (Live/Demo): demo
Traceback (most recent call last):
  File "testproto.py", line 11, in <module>
    client = Client(host, EndPoints.PROTOBUF_PORT, TcpProtocol)
  File "/home/baotd/Documents/bot-trader/collection-engine/.venv/lib/python3.8/site-packages/ctrader_open_api/client.py", line 13, in __init__
    endpoint = clientFromString(self._runningReactor, f"ssl:{host}:{port}")
  File "/home/baotd/Documents/bot-trader/collection-engine/.venv/lib/python3.8/site-packages/twisted/internet/endpoints.py", line 2116, in clientFromString
    kwargs = _clientParsers[name](*args, **kwargs)
  File "/home/baotd/Documents/bot-trader/collection-engine/.venv/lib/python3.8/site-packages/twisted/internet/endpoints.py", line 2000, in _parseClientSSL
    return _parseClientSSLOptions(kwargs)
  File "/home/baotd/Documents/bot-trader/collection-engine/.venv/lib/python3.8/site-packages/twisted/internet/endpoints.py", line 1965, in _parseClientSSLOptions
    configuration = CertificateOptions(
NameError: name 'CertificateOptions' is not defined
```

Version:
- python 3.8
- ctrader-open-api = "^0.9.1"
- protobuf = "3.20.1"
- Twisted = "21.7.0"

I think the issue relate to Twisted.

- Could you help me figure out this issue?
- Could you please write unit test to make sure everything is fine?

Thank you

**Comment by panxw** [comment]
I tried to install `pyopenssl` by pip, then it works,  maybe you could have a try!

**Comment by panxw** [comment]
I tried to install `pyopenssl` by pip, then it works,  maybe you could have a try!
