### ISSUE TITLE
Can't run the jupyter sample

### ISSUE THREAD

**Issue by Sin13** [spotware/OpenApiPy#24]
When i try to execute `reactor.run()` in the jupyter sample, i get the following error:
```
Unhandled Error
Traceback (most recent call last):
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/python/log.py", line 85, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 691, in _doReadOrWrite
    why = selectable.doWrite()
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/tcp.py", line 614, in doConnect
    self._connectDone()
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/tcp.py", line 642, in _connectDone
    self.protocol.makeConnection(self)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/protocols/tls.py", line 211, in makeConnection
    ProtocolWrapper.makeConnection(self, transport)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/protocols/policies.py", line 74, in makeConnection
    self.wrappedProtocol.makeConnection(self)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/protocol.py", line 508, in makeConnection
    self.connectionMade()
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/endpoints.py", line 142, in connectionMade
    self._wrappedProtocol.makeConnection(self.transport)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/protocol.py", line 508, in makeConnection
    self.connectionMade()
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/ctrader_open_api/tcpProtocol.py", line 21, in connectionMade
    self.factory.connected(self)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/ctrader_open_api/factory.py", line 11, in connected
    self.client._connected(protocol)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/ctrader_open_api/client.py", line 33, in _connected
    asyncio.run(self._connectedCallback(self))
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/asyncio/runners.py", line 33, in run
    raise RuntimeError(
builtins.RuntimeError: asyncio.run() cannot be called from a running event loop

Unhandled Error
Traceback (most recent call last):
  File "/tmp/ipykernel_6723/2480525364.py", line 4, in <module>
    reactor.run()
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/base.py", line 1331, in mainLoop
    reactorBaseSelf.doIteration(t)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/epollreactor.py", line 244, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/python/log.py", line 85, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 699, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 306, in _disconnectSelectable
    selectable.connectionLost(failure.Failure(why))
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/tcp.py", line 507, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/tcp.py", line 325, in connectionLost
    protocol.connectionLost(reason)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/protocols/tls.py", line 394, in connectionLost
    ProtocolWrapper.connectionLost(self, reason)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/protocols/policies.py", line 113, in connectionLost
    self.wrappedProtocol.connectionLost(reason)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/internet/endpoints.py", line 161, in connectionLost
    return self._wrappedProtocol.connectionLost(reason)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/application/internet.py", line 467, in connectionLost
    self._lostNotification(reason)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/twisted/application/internet.py", line 660, in <lambda>
    self._factory, lambda _: self._clientDisconnected()
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/automat/_methodical.py", line 235, in _clientDisconnected
    (outputs, outTracer) = transitioner.transition(self)
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/automat/_core.py", line 157, in transition
    outState, outputSymbols = self._automaton.outputForInput(self._state,
  File "/home/sina/miniconda3/envs/strader/lib/python3.10/site-packages/automat/_core.py", line 137, in outputForInput
    raise NoTransition(state=inState, symbol=inputSymbol)
automat._core.NoTransition: no transition for MethodicalInput(method=<function _ClientMachine._clientDisconnected at 0x7f4d1e94f520>) in MethodicalState(method=<function _ClientMachine._connecting at 0x7f4d1e94e8c0>)


Connected

Disconnected:  [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion: Connection lost.
]
```

Please note that at the time of writing this issue, the market is closed. so maybe the `NoTransition` error is referring to that. but in any case i shouldn't get an `unhandled error` when I'm just trying to authenticate.
Maybe i would need to check my account balance or my open positions or submit a pending order in the market closed time and the fact that the market is closed shouldn't stop my application from sending such requests.

**Comment by Sin13** [comment]
Update:

Turns out it had nothing to do with market close time. i had some dependency issues and i had to uninstall this package and all of it dependencies and install them again.

That solved my problem, so I'm closing this issue.
